# Generated by Django 2.2 on 2019-05-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190516_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('can_view', 'Can view doctor'), ('can_add', 'Can add doctor'), ('can_see', 'Can see doctor'), ('can_edit', 'Can edit doctor'), ('can_delete', 'Can delete doctor'))},
        ),
    ]
